# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Maven image to build the project
FROM maven:3.8.4-openjdk-17 AS builder

# Set the working directory
WORKDIR /app

# Copy the Maven project file
COPY pom.xml .

# Copy the source code
COPY src ./src

# Package the application
RUN mvn install -DskipTests

# Use the JBang base image to run the application
FROM jbangdev/jbang:latest

# Copy the packaged JAR from the builder image
COPY --from=builder /app/target/*.jar /app/weather-runner.jar

# Set the working directory
WORKDIR /app

# Run the application using JBang
ENTRYPOINT ["jbang", "--quiet", "/app/weather-runner.jar"]
