#!/usr/bin/env python3
"""Validate or apply explicit kebab-case heading IDs in MCP server docs.

Implements the convention agreed in quarkiverse/quarkus-langchain4j#2401 and
confirmed by mkouba in quarkiverse/quarkus-mcp-server#765:
every section heading (level 1-5) under docs/modules/ROOT/pages/ must be
preceded by an explicit `[id="kebab-case-id"]` block attribute.

Usage:
    python docs/scripts/check-heading-ids.py --check       # CI-friendly, exit 1 on violations
    python docs/scripts/check-heading-ids.py --fix         # rewrite files in place
    python docs/scripts/check-heading-ids.py --self-test   # run inline assertions

Scope: docs/modules/ROOT/pages/ excluding pages/includes/ (auto-generated).

Generated by Claude Code.
"""
from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCOPE_ROOT = REPO_ROOT / "docs" / "modules" / "ROOT" / "pages"
EXCLUDE_DIR = SCOPE_ROOT / "includes"

HEADING_RE = re.compile(r"^(==+)\s+(.+?)\s*$")
BLOCK_ATTR_RE = re.compile(r"^\[.*\]\s*$")
LEGACY_ANCHOR_RE = re.compile(r"^\[\[([^\]]+)\]\]\s*$")
ID_ATTR_RE = re.compile(r'\bid\s*=\s*"([^"]+)"')
SHORTHAND_ID_RE = re.compile(r"^\[#([^,\s\]]+)")
KEBAB_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")

FENCE_PATTERNS = {
    "listing": re.compile(r"^-{4,}\s*$"),
    "literal": re.compile(r"^\.{4,}\s*$"),
    "passthrough": re.compile(r"^\+{4,}\s*$"),
    "comment": re.compile(r"^/{4,}\s*$"),
    "example": re.compile(r"^={4,}\s*$"),
}


@dataclass
class Violation:
    path: Path
    line: int
    kind: str
    detail: str

    def format(self) -> str:
        rel = self.path.relative_to(REPO_ROOT)
        return f"{rel}:{self.line}: [{self.kind}] {self.detail}"


def iter_in_scope_files() -> list[Path]:
    files = []
    for p in sorted(SCOPE_ROOT.rglob("*.adoc")):
        try:
            p.relative_to(EXCLUDE_DIR)
        except ValueError:
            files.append(p)
    return files


def derive_id(text: str) -> str:
    s = text
    s = re.sub(r"`([^`]+)`", r"\1", s)
    s = re.sub(r"xref:[^\[]+\[([^\]]*)\]", r"\1", s)
    s = re.sub(r"link:[^\[]+\[([^\]]*)\]", r"\1", s)
    s = re.sub(r"\{[^}]+\}", " ", s)
    s = re.sub(r"[*_]+([^*_]+)[*_]+", r"\1", s)
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = s.strip("-")
    return s


def is_fence(line: str) -> str | None:
    for kind, pat in FENCE_PATTERNS.items():
        if pat.match(line):
            return kind
    return None


def extract_existing_id(attr_line: str) -> str | None:
    """Return the ID declared on a block-attribute line, if any."""
    m = ID_ATTR_RE.search(attr_line)
    if m:
        return m.group(1)
    m = SHORTHAND_ID_RE.match(attr_line)
    if m:
        return m.group(1)
    return None


def scan_file(path: Path):
    """Yield (heading_line_idx, level, heading_text, attr_stack_start_idx, attr_stack)
    for each in-scope heading.

    attr_stack is the list of consecutive block-attribute lines directly above
    the heading (with no blank line between). attr_stack_start_idx is the
    line index of the topmost attribute line, or the heading index if the
    stack is empty.
    """
    lines = path.read_text(encoding="utf-8").splitlines()
    open_fence: str | None = None
    headings = []
    for i, line in enumerate(lines):
        fence = is_fence(line)
        if fence:
            if open_fence is None:
                open_fence = fence
            elif open_fence == fence:
                open_fence = None
            continue
        if open_fence is not None:
            continue
        m = HEADING_RE.match(line)
        if not m:
            continue
        level = len(m.group(1))  # 2 = h1 (==), 6 = h5 (======)
        if level < 2:  # defensive; regex requires =={2,} so always true
            continue
        text = m.group(2).strip()

        # Walk upward through consecutive block-attribute lines (no blank line between).
        stack = []
        j = i - 1
        while j >= 0 and BLOCK_ATTR_RE.match(lines[j]):
            stack.append((j, lines[j]))
            j -= 1
        stack.reverse()
        attr_start_idx = stack[0][0] if stack else i
        headings.append((i, level, text, attr_start_idx, stack, lines))
    return lines, headings


def check_file(path: Path) -> list[Violation]:
    violations: list[Violation] = []
    _, headings = scan_file(path)
    seen_ids: dict[str, int] = {}

    for heading_idx, _level, text, _attr_start_idx, stack, lines in headings:
        existing_id = None
        legacy_anchor = None

        for _idx, attr_line in stack:
            eid = extract_existing_id(attr_line)
            if eid is not None:
                existing_id = eid
                break
        if existing_id is None and stack:
            last_idx, last_line = stack[-1]
            legacy_match = LEGACY_ANCHOR_RE.match(last_line)
            if legacy_match:
                legacy_anchor = legacy_match.group(1)
                violations.append(
                    Violation(
                        path,
                        last_idx + 1,
                        "legacy-anchor",
                        f"`[[{legacy_anchor}]]` should be `[id=\"{legacy_anchor}\"]`",
                    )
                )

        if existing_id is None and legacy_anchor is None:
            violations.append(
                Violation(
                    path,
                    heading_idx + 1,
                    "missing-id",
                    f"heading {text!r} has no `[id=\"...\"]`",
                )
            )
            continue

        effective_id = existing_id if existing_id is not None else legacy_anchor
        if effective_id is not None:
            if not KEBAB_RE.match(effective_id):
                violations.append(
                    Violation(
                        path,
                        heading_idx + 1,
                        "non-kebab",
                        f"id {effective_id!r} is not kebab-case",
                    )
                )
            if effective_id in seen_ids:
                violations.append(
                    Violation(
                        path,
                        heading_idx + 1,
                        "duplicate-id",
                        f"id {effective_id!r} also declared at line {seen_ids[effective_id]}",
                    )
                )
            else:
                seen_ids[effective_id] = heading_idx + 1
    return violations


def fix_file(path: Path) -> int:
    """Apply --fix to one file. Returns number of edits made."""
    lines, headings = scan_file(path)
    edits = 0

    used_ids: set[str] = set()
    # Pre-collect existing IDs so we don't collide when generating new ones.
    for _h_idx, _level, _text, _start, stack, _ in headings:
        for _idx, attr_line in stack:
            eid = extract_existing_id(attr_line)
            if eid:
                used_ids.add(eid)

    # Process headings bottom-up so line indices remain valid as we insert/replace.
    for heading_idx, _level, text, attr_start_idx, stack, _ in reversed(headings):
        existing_id = None
        legacy_idx = None
        legacy_anchor = None

        for idx, attr_line in stack:
            eid = extract_existing_id(attr_line)
            if eid is not None:
                existing_id = eid
                break
        if existing_id is None and stack:
            last_idx, last_line = stack[-1]
            m = LEGACY_ANCHOR_RE.match(last_line)
            if m:
                legacy_idx = last_idx
                legacy_anchor = m.group(1)

        if existing_id is not None:
            continue
        if legacy_anchor is not None:
            lines[legacy_idx] = f'[id="{legacy_anchor}"]'
            edits += 1
            used_ids.add(legacy_anchor)
            continue

        base = derive_id(text)
        if not base:
            base = "section"
        new_id = base
        n = 2
        while new_id in used_ids:
            new_id = f"{base}-{n}"
            n += 1
        used_ids.add(new_id)
        lines.insert(attr_start_idx, f'[id="{new_id}"]')
        edits += 1

    if edits:
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return edits


def cmd_check() -> int:
    files = iter_in_scope_files()
    all_violations: list[Violation] = []
    for f in files:
        all_violations.extend(check_file(f))
    if not all_violations:
        print(f"OK: {len(files)} files clean", file=sys.stderr)
        return 0
    by_path: dict[Path, list[Violation]] = {}
    for v in all_violations:
        by_path.setdefault(v.path, []).append(v)
    for p in sorted(by_path):
        for v in by_path[p]:
            print(v.format())
    print(
        f"\nFAIL: {len(all_violations)} violation(s) in {len(by_path)} file(s)",
        file=sys.stderr,
    )
    return 1


def cmd_fix() -> int:
    files = iter_in_scope_files()
    total_edits = 0
    edited_files = 0
    for f in files:
        n = fix_file(f)
        if n:
            edited_files += 1
            total_edits += n
            print(f"{f.relative_to(REPO_ROOT)}: {n} edit(s)")
    print(f"\n{total_edits} edit(s) across {edited_files} file(s)")
    return 0


def cmd_self_test() -> int:
    failures: list[str] = []

    def expect(actual, expected, label):
        if actual != expected:
            failures.append(f"{label}: expected {expected!r}, got {actual!r}")

    expect(derive_id("Building Your First Tool"), "building-your-first-tool", "basic")
    expect(derive_id("Configure the `application.properties` file"),
           "configure-the-application-properties-file", "backticks")
    expect(derive_id("OIDC: how to authenticate"), "oidc-how-to-authenticate", "punctuation")
    expect(derive_id("xref:foo.adoc[Linked text] in heading"),
           "linked-text-in-heading", "xref-macro")
    expect(derive_id("Use {project-name} attributes"), "use-attributes", "attribute-ref")
    expect(derive_id("**Bold** and _italic_ text"), "bold-and-italic-text", "inline-markup")
    expect(derive_id("Multiple   spaces"), "multiple-spaces", "whitespace-collapse")
    expect(derive_id("---trim---"), "trim", "trim-dashes")

    expect(KEBAB_RE.match("hello-world") is not None, True, "kebab-valid")
    expect(KEBAB_RE.match("Hello-World") is not None, False, "kebab-uppercase")
    expect(KEBAB_RE.match("hello_world") is not None, False, "kebab-underscore")
    expect(KEBAB_RE.match("hello--world") is not None, False, "kebab-double-hyphen")
    expect(KEBAB_RE.match("123-abc") is not None, True, "kebab-numeric-start")

    expect(is_fence("----"), "listing", "fence-listing")
    expect(is_fence("------"), "listing", "fence-listing-long")
    expect(is_fence("===="), "example", "fence-example")
    expect(is_fence("==== Heading"), None, "fence-not-heading")
    expect(is_fence("== Heading"), None, "fence-h1-not-fence")
    expect(is_fence("...."), "literal", "fence-literal")
    expect(is_fence("////"), "comment", "fence-comment")
    expect(is_fence("++++"), "passthrough", "fence-passthrough")

    expect(extract_existing_id('[id="foo-bar"]'), "foo-bar", "id-extract-canonical")
    expect(extract_existing_id('[role="x", id="bar"]'), "bar", "id-extract-mixed")
    expect(extract_existing_id("[#shorthand-id]"), "shorthand-id", "id-extract-shorthand")
    expect(extract_existing_id('[role="x"]'), None, "id-extract-none")
    expect(extract_existing_id("[#sh-id, role=x]"), "sh-id", "id-extract-shorthand-mixed")

    if failures:
        for f in failures:
            print(f"FAIL: {f}")
        print(f"\n{len(failures)} self-test failure(s)", file=sys.stderr)
        return 1
    print("self-test: all assertions passed", file=sys.stderr)
    return 0


def main(argv: list[str]) -> int:
    args = argv[1:] or ["--check"]
    if "--self-test" in args:
        return cmd_self_test()
    if "--fix" in args:
        return cmd_fix()
    if "--check" in args:
        return cmd_check()
    print(f"unknown args: {args}", file=sys.stderr)
    print("usage: check-heading-ids.py [--check|--fix|--self-test]", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
