quarkus.mcp.server.sse.root-path=/

# MCP HTTP SSE endpoint is secured by GitHub provider.
quarkus.oidc.provider=github
quarkus.oidc.client-id=${github.client.id}
quarkus.oidc.credentials.secret=${github.client.secret}
# Override the default `web-app` application type for the GitHub provider to require that an access token is sent to the SSE endpoint
quarkus.oidc.application-type=service

# Support for secure login endpoint that can return a GitHub access token to the user 
quarkus.oidc.login.provider=github
quarkus.oidc.login.client-id=${quarkus.oidc.client-id}
quarkus.oidc.login.credentials.secret=${quarkus.oidc.credentials.secret}

# MCP SSE endpoint is not implemented as a JAX-RS endpoint where an annotation could've been used, therefore
# HTTP security policy configuration must be used to trigger a security check when the SSE endpoint is accessed
quarkus.http.auth.permission.authenticated.paths=/sse    
quarkus.http.auth.permission.authenticated.policy=authenticated

# We are doing this so that we can run the jar file directly using `jbang org.acme:secure-http-server:1.0.0-SNAPSHOT:runner`
quarkus.package.jar.type=uber-jar
