quarkus.mcp.server.beta.sse.root-path=/beta/mcp

quarkus.http.auth.permission.authenticated.paths=/mcp/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.http.auth.permission.beta.paths=/beta/mcp/*
quarkus.http.auth.permission.beta.policy=phone-scope-required
quarkus.http.auth.policy.phone-scope-required.roles-allowed=phone

quarkus.oidc.tenant-paths=/mcp/*
quarkus.oidc.token.audience=quarkus-mcp-alpha
quarkus.oidc.resource-metadata.enabled=true
quarkus.oidc.resource-metadata.force-https-scheme=false

quarkus.oidc.beta.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.beta.tenant-paths=/beta/mcp/*
quarkus.oidc.beta.token.audience=quarkus-mcp-alpha
quarkus.oidc.beta.roles.role-claim-path=scope
quarkus.oidc.beta.resource-metadata.enabled=true
quarkus.oidc.beta.resource-metadata.resource=beta/mcp
quarkus.oidc.beta.resource-metadata.force-https-scheme=false

quarkus.oidc.code-flow.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.code-flow.tenant-paths=/access-token
quarkus.oidc.code-flow.application-type=web-app
quarkus.oidc.code-flow.client-id=alpha-client
quarkus.oidc.code-flow.authentication.scopes=quarkus-mcp-alpha

quarkus.oidc.code-flow-no-audience.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.code-flow-no-audience.tenant-paths=/access-token-no-audience
quarkus.oidc.code-flow-no-audience.application-type=web-app
quarkus.oidc.code-flow-no-audience.client-id=alpha-client

quarkus.oidc.code-flow-phone-scope.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.code-flow-phone-scope.tenant-paths=/access-token-phone-scope
quarkus.oidc.code-flow-phone-scope.application-type=web-app
quarkus.oidc.code-flow-phone-scope.client-id=alpha-client
quarkus.oidc.code-flow-phone-scope.authentication.scopes=quarkus-mcp-alpha,phone

quarkus.keycloak.devservices.realm-path=alpha-realm.json

quarkus.log.category."org.htmlunit".level=ERROR

%test.quarkus.test.enable-callbacks-for-integration-tests=true
