quarkus.http.auth.permission.authenticated.paths=/mcp/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.oidc.tenant-paths=/mcp/*
quarkus.oidc.token.audience=quarkus-mcp-alpha
quarkus.oidc.resource-metadata.enabled=true
quarkus.oidc.resource-metadata.force-https-scheme=false

quarkus.oidc.code-flow.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.code-flow.tenant-paths=/access-token
quarkus.oidc.code-flow.application-type=web-app
quarkus.oidc.code-flow.client-id=alpha-client
quarkus.oidc.code-flow.authentication.scopes=quarkus-mcp-alpha

quarkus.oidc.code-flow-no-audience.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.code-flow-no-audience.tenant-paths=/access-token-no-audience
quarkus.oidc.code-flow-no-audience.application-type=web-app
quarkus.oidc.code-flow-no-audience.client-id=alpha-client

quarkus.keycloak.devservices.realm-path=alpha-realm.json

quarkus.log.category."org.htmlunit".level=ERROR

%test.quarkus.test.enable-callbacks-for-integration-tests=true
