package io.quarkiverse.mcp.server.deployment;

import io.quarkus.builder.item.MultiBuildItem;

/**
 * Generated by MCP transport implementations to advertise their existence
 */
public final class TransportCandidateBuildItem extends MultiBuildItem {

    private final String name;

    public TransportCandidateBuildItem(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
